In [1]:
import pandas as pd
import numpy as np

In [2]:
camping_df = pd.read_csv('camping_res21.csv')

In [4]:
camping_df.head()

,ParkName,ParkId,FacilityName,FacilityId,UnitName,UseType,UnitSpec,IsAda,IsTentSite,IsRvSite,VehicleLength,UnitType,ArrivalDate
0,Anza-Borrego Desert SP,2,Borrego Palm Canyon (sites 90-120),777,103,Nightly,Campsite,False,True,True,25,Camping,2/11/21 0:00
1,Anza-Borrego Desert SP,2,Borrego Palm Canyon (sites 90-120),777,103,Nightly,Campsite,False,True,True,25,Camping,3/10/21 0:00
2,Anza-Borrego Desert SP,2,Borrego Palm Canyon (sites 90-120),777,103,Nightly,Campsite,False,True,True,25,Camping,3/4/21 0:00
3,Anza-Borrego Desert SP,2,Borrego Palm Canyon (sites 90-120),777,103,Nightly,Campsite,False,True,True,25,Camping,2/3/21 0:00
4,Anza-Borrego Desert SP,2,Borrego Palm Canyon (sites 90-120),777,103,Nightly,Campsite,False,True,True,25,Camping,3/24/21 0:00

In [5]:
camping_df.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63179 entries, 0 to 63178
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ParkName       63179 non-null  object
 1   ParkId         63179 non-null  int64
 2   FacilityName   63179 non-null  object
 3   FacilityId     63179 non-null  int64
 4   UnitName       63179 non-null  object
 5   UseType        63179 non-null  object
 6   UnitSpec       63179 non-null  object
 7   IsAda          63179 non-null  bool
 8   IsTentSite     63179 non-null  bool
 9   IsRvSite       63179 non-null  bool
 10  VehicleLength  63179 non-null  int64
 11  UnitType       63179 non-null  object
 12  ArrivalDate    63179 non-null  object
dtypes: bool(3), int64(3), object(7)
memory usage: 5.0+ MB

In [7]:
camping_df[['FacilityName', 'UnitType']].head()

                         FacilityName UnitType
0  Borrego Palm Canyon (sites 90-120)  Camping
1  Borrego Palm Canyon (sites 90-120)  Camping
2  Borrego Palm Canyon (sites 90-120)  Camping
3  Borrego Palm Canyon (sites 90-120)  Camping
4  Borrego Palm Canyon (sites 90-120)  Camping